<?php

namespace SOSVelo\Bundle\PointBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PointCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointCommentRepository extends EntityRepository
{
}
