sos_velo_template:
    resource: "@SOSVeloTemplateBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /optional_routing_prefix

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    
sosvelo_user_get:
    type: annotation
    resource: SOSVelo\Bundle\UserBundle\Controller\UserController
    
sosvelo_comment_get:
    type: annotation
    resource: SOSVelo\Bundle\CommentBundle\Controller\CommentController

sosvelo_point_get:
    type: annotation
    resource: SOSVelo\Bundle\PointBundle\Controller\PointController

sosvelo_home:
    path:     /home
    defaults: { _controller: SOSVeloTemplateBundle:Template:index }
    
sosvelo_add_point:
    path:     /add_point
    defaults: { _controller: SOSVeloPointBundle:Point:add_point }
    requirements:
        _method:  GET|POST


